### ISSUE TITLE
Database Error during make demo

### ISSUE THREAD

**Issue by beatreichenbach** [ynput/ayon-docker#18]
I followed the installation instructions and everything worked well until the the creation of the demo projects. I'm getting this when running the `make demo` command:

```
sudo make demo
docker compose exec -T server python -m demogen < demo/feature.json;  docker compose exec -T server python -m demogen < demo/commercial.json;  docker compose exec -T server python -m demogen < demo/episodic.json;
2023-09-26 11:16:43 INFO       Log collector initialized
2023-09-26 11:16:44 INFO       Connecting to database
2023-09-26 11:16:44 INFO       Deleting old project if exists
2023-09-26 11:16:45 INFO       Creating folders for project demo_Big_Feature
Traceback (most recent call last):
  File "/backend/ayon_server/entities/core/projectlevel.py", line 247, in save
    await transaction.execute(
  File "/usr/local/lib/python3.11/site-packages/asyncpg/connection.py", line 319, in execute
    _, status, _ = await self._execute(
                   ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/asyncpg/connection.py", line 1658, in _execute
    result, _ = await self.__execute(
                ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/asyncpg/connection.py", line 1683, in __execute
    return await self._do_execute(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/asyncpg/connection.py", line 1730, in _do_execute
    result = await executor(stmt, None)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "asyncpg/protocol/protocol.pyx", line 201, in bind_execute
asyncpg.exceptions.ForeignKeyViolationError: insert or update on table "workfiles" violates foreign key constraint "workfiles_created_by_fkey"
DETAIL:  Key (created_by)=(admin) is not present in table "users".
```

There are several more errors but always with the same ConstraintViolationException.

**Comment by johhnry** [comment]
Hi,

I have the same issue on [65079d8](https://github.com/ynput/ayon-docker/commit/65079d8a79393094fa61574ccfaa18f9cb786cdf). This is the steps I followed:

```shell
$ git clone https://github.com/ynput/ayon-docker.git
$ cd ayon-docker
$ docker compose up -d

# Create the admin account in the UI on http://<host>:5000

$ make demo
```

```
docker compose exec -T server python -m demogen < demo/commercial.json;  docker compose exec -T server python -m demogen < demo/episodic.json;  docker compose exec -T server python -m demogen < demo/feature.json;
2023-10-27 09:13:00 INFO       Log collector initialized
2023-10-27 09:13:00 INFO       Connecting to database
2023-10-27 09:13:01 INFO       Deleting old project if exists
2023-10-27 09:13:01 INFO       Creating folders for project demo_Commercial
Traceback (most recent call last):
  File "/backend/ayon_server/entities/core/projectlevel.py", line 247, in save
    await transaction.execute(
  File "/usr/local/lib/python3.11/site-packages/asyncpg/connection.py", line 319, in execute
    _, status, _ = await self._execute(
                   ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/asyncpg/connection.py", line 1658, in _execute
    result, _ = await self.__execute(
                ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/asyncpg/connection.py", line 1683, in __execute
    return await self._do_execute(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/asyncpg/connection.py", line 1730, in _do_execute
    result = await executor(stmt, None)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "asyncpg/protocol/protocol.pyx", line 201, in bind_execute
asyncpg.exceptions.ForeignKeyViolationError: insert or update on table "workfiles" violates foreign key constraint "workfiles_created_by_fkey"
DETAIL:  Key (created_by)=(admin) is not present in table "users".

...
```

And there are also more errors

Thanks!
