### ISSUE TITLE
Arm64 support

### ISSUE THREAD

**Issue by Randalix** [ynput/ayon-docker#28]
Can we get arm64 support?

**Comment by martastain** [comment]
That would be nice indeed. Are you interested in running on mac or a generic arm server?

Could you try building the image yourself using `make build` command on your platform?

**Comment by Randalix** [comment]
Thanks for your reply! My server is a m1 mini running debian.
I tried to build the server, but I'm stuck with the mypy strawberry plugin.
```
$ make check
sed -i "s/^version = \".*\"/version = \"1.0.11\"/" pyproject.toml
poetry run ruff check . --select=I --fix
poetry run ruff format .
275 files left unchanged
poetry run ruff check . --fix
poetry run mypy .
mypy.ini:9: error: Error importing plugin "strawberry.ext.mypy_plugin": No module named 'strawberry'  [misc]
Found 1 error in 1 file (errors prevented further checking)
make: *** [Makefile:12: check] Error 2
```
I've installed it using venv and pip. When I run a python interactive console, I can import strawberry.

**Comment by Randalix** [comment]
I'm running debian on a m1 mac.
I've tried to build the server, but currently I'm stuck here:
```
$ make check
sed -i "s/^version = \".*\"/version = \"1.0.11\"/" pyproject.toml
poetry run ruff check . --select=I --fix
poetry run ruff format .
275 files left unchanged
poetry run ruff check . --fix
poetry run mypy .
ayon_server/addons/addon.py:550: error: Item "None" of "BaseSettingsModel | None" has no attribute "dict"  [union-attr]
Found 1 error in 1 file (checked 261 source files)
make: *** [Makefile:12: check] Error 1
```
Will give it another try tomorrow.

**Comment by martastain** [comment]
You don't need to use the Makefile in ayon-backend repo. This (ayon-docker) repository has its own makefile with "build" target. 

It should clone both backend and frontend locally and build a local copy of `ynput/ayon:latest` image, which you can then use. I assume it SHOULD build it based on your platform.

You may also need to tweak the Dockerfile to use the correct base images - honestly, I am not sure about that part, but both node and python images used in the dockerfile have their arm64v8 equivalents:

https://hub.docker.com/r/arm64v8/python/
https://hub.docker.com/r/arm64v8/node/

**Comment by ballinger** [comment]
same issue here

**Comment by martastain** [comment]
Out of the curiosity - what platform do you use? Ampere?

**Comment by ballinger** [comment]
I usually just test stuff with it...it's a PI 4 - latest 64bit Debian OS

**Comment by martastain** [comment]
Gotcha. I doubt we'll support RaPi natively as it... Well... Doesn't make much sense, but have you tried building the image yourself? I wonder if that works or has unresolvable dependencies

**Comment by ballinger** [comment]
Couldn't find a normal compile guide and only got docker on the pi...

**Comment by Redwolf223** [comment]
I've manage to build the image, and start postgres + redis using qemu. 

The only problem is that when trying to start the ayon-docker-server the log says:

`ayon-docker-server-1    | 2024-08-25 22:32:34 ERROR      server          Unable to initialize users
ayon-docker-server-1    |
ayon-docker-server-1    |     Traceback (most recent call last):
ayon-docker-server-1    |       File "/backend/ayon_server/api/server.py", line 292, in init_api
ayon-docker-server-1    |         module = importlib.import_module(module_name)
ayon-docker-server-1    |                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ayon-docker-server-1    |       File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
ayon-docker-server-1    |         return _bootstrap._gcd_import(name[level:], package, level)
ayon-docker-server-1    |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ayon-docker-server-1    |       File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
ayon-docker-server-1    |       File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
ayon-docker-server-1    |       File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
ayon-docker-server-1    |       File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
ayon-docker-server-1    |       File "<frozen importlib._bootstrap_external>", line 940, in exec_module
ayon-docker-server-1    |       File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
ayon-docker-server-1    |       File "/backend/api/users/__init__.py", line 3, in <module>
ayon-docker-server-1    |         from . import avatar, password_reset, users
ayon-docker-server-1    |       File "/backend/api/users/avatar.py", line 14, in <module>
ayon-docker-server-1    |         from ayon_server.helpers.thumbnails import process_thumbnail
ayon-docker-server-1    |       File "/backend/ayon_server/helpers/thumbnails.py", line 5, in <module>
ayon-docker-server-1    |         from PIL import Image
ayon-docker-server-1    |       File "/usr/local/lib/python3.11/site-packages/PIL/Image.py", line 100, in <module>
ayon-docker-server-1    |         from . import _imaging as core
ayon-docker-server-1    |     ImportError: libXau-154567c4.so.6.0.0: failed to map segment from shared object
`

I'm currently on a raspberry pi 5.
