### ISSUE TITLE
Ayon Docker Setup [Tested: LTS Ubuntu 24.04]

### ISSUE THREAD

**Issue by Ballard-dev** [ynput/ayon-docker#29]
> postgres-1  | 2024-05-17 12:11:20.150 UTC [209] FATAL:  password authentication failed for user "ayon"
> postgres-1  | 2024-05-17 12:11:20.150 UTC [209] DETAIL:  Role "ayon" does not exist.
> postgres-1  |   Connection matched pg_hba.conf line 100: "host all all all scram-sha-256"
> server-1    | 2024-05-17 12:11:20 ERROR      setup           Exception!
> server-1    |
> server-1    |     Traceback (most recent call last):
> server-1    |       File "/backend/setup/__main__.py", line 42, in wait_for_postgres
> server-1    |         await Postgres.connect()
> server-1    |       File "/backend/ayon_server/lib/postgres.py", line 89, in connect
> server-1    |         cls.pool = await asyncpg.create_pool(
> server-1    |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^
> server-1    |       File "/usr/local/lib/python3.11/site-packages/asyncpg/pool.py", line 403, in _async__init__
> server-1    |         await self._initialize()
> server-1    |       File "/usr/local/lib/python3.11/site-packages/asyncpg/pool.py", line 430, in _initialize
> server-1    |         await first_ch.connect()
> server-1    |       File "/usr/local/lib/python3.11/site-packages/asyncpg/pool.py", line 128, in connect
> server-1    |         self._con = await self._pool._get_new_connection()
> server-1    |                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> server-1    |       File "/usr/local/lib/python3.11/site-packages/asyncpg/pool.py", line 502, in _get_new_connection
> server-1    |         con = await connection.connect(
> server-1    |               ^^^^^^^^^^^^^^^^^^^^^^^^^
> server-1    |       File "/usr/local/lib/python3.11/site-packages/asyncpg/connection.py", line 2329, in connect
> server-1    |         return await connect_utils._connect(
> server-1    |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> server-1    |       File "/usr/local/lib/python3.11/site-packages/asyncpg/connect_utils.py", line 991, in _connect
> server-1    |         conn = await _connect_addr(
> server-1    |                ^^^^^^^^^^^^^^^^^^^^
> server-1    |       File "/usr/local/lib/python3.11/site-packages/asyncpg/connect_utils.py", line 828, in _connect_addr
> server-1    |         return await __connect_addr(params, True, *args)
> server-1    |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> server-1    |       File "/usr/local/lib/python3.11/site-packages/asyncpg/connect_utils.py", line 876, in __connect_addr
> server-1    |         await connected
> server-1    |     asyncpg.exceptions.InvalidPasswordError: password authentication failed for user "ayon"

Following the steps: https://ayon.ynput.io/docs/admin_server_deployment/

After running Step 6 I ran `docker ps` to check the status of the containers. The core container with image `ynput/ayon:latest` is `unheathy` and after checking the logs the error is presented as above.

When I exec into the postgres container I was also unable to login to the database with any number of users I'd attempted.

My studio would prefer to run on this OS, please let me know if there are any outstanding issues to be resolved related to this so that we can move forward with the product!

Thanks!

**Comment by Ballard-dev** [comment]
Found a workaround
